### ISSUE TITLE
No modules named eval_classification, eval_msrp, eval_sick, eval_trec, ...

### ISSUE THREAD

**Issue by tuvuumass** [lajanugen/S2V#1]
I couldn't find some modules, i.e, eval_classification, eval_msrp, eval_sick, eval_trec, ... in evaluate.py.

**Comment by angelazhao7** [comment]
I have the same issue

**Comment by angela-zhao** [comment]
@tuvuumass Those modules are in the skip-thoughts repo. You can copy and paste them into the S2V repo.
